# Generated by Django 4.2.2 on 2025-01-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ful", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите частый вопрос",
                        max_length=100,
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Введите ответ на вопрос",
                        verbose_name="Ответ на вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите услугу",
                        max_length=100,
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание услуги",
                        verbose_name="Описание услуги",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="Введите стоимость услуги",
                        verbose_name="Стоимость услуги",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение услуги",
                        null=True,
                        upload_to="services/image",
                        verbose_name="Изображение услуги (превью)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
