# Generated by Django 4.2.2 on 2025-01-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ful", "0002_faq_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите категорию вопроса",
                        max_length=100,
                        verbose_name="Категория вопроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория вопроса",
                "verbose_name_plural": "Категории вопросов",
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите категорию вопроса",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ful.categoryfaq",
                verbose_name="Категория",
            ),
        ),
    ]
