# Generated by Django 4.2.2 on 2025-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ful", "0005_alter_faq_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="measurement",
            field=models.CharField(
                blank=True,
                help_text="Введите единицу измерения",
                max_length=100,
                null=True,
                verbose_name="Единица измерения",
            ),
        ),
    ]
