# Generated by Django 4.2.2 on 2025-01-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ful", "0006_services_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание услуги",
                null=True,
                verbose_name="Описание услуги",
            ),
        ),
    ]
