# Generated by Django 4.2.2 on 2025-01-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ful", "0007_alter_services_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите должность",
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название склада",
                        max_length=100,
                        verbose_name="Название склада",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Укажите город, где находится склад",
                        max_length=30,
                        verbose_name="Город нахождения склада",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Укажите адрес склада",
                        max_length=100,
                        verbose_name="Адрес склада",
                    ),
                ),
                (
                    "slag",
                    models.SlugField(
                        blank=True,
                        help_text="Можно вручную исправить URL",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию склада",
                        null=True,
                        upload_to="warehouses/image",
                        verbose_name="фотография склада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию сотрудника",
                        max_length=30,
                        verbose_name="Фамилия сотрудника",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя сотрудника",
                        max_length=30,
                        verbose_name="Имя сотрудника",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию",
                        null=True,
                        upload_to="employees/image",
                        verbose_name="фотография сотрудника",
                    ),
                ),
                (
                    "job_title",
                    models.ForeignKey(
                        blank=True,
                        help_text="На каком должности работает сотрудник?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_title",
                        to="ful.jobtitle",
                        verbose_name="Должность сотрудника",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="На каком складе работает сотрудник?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse",
                        to="ful.warehouses",
                        verbose_name="Склад",
                    ),
                ),
            ],
        ),
    ]
