# Generated by Django 4.2.2 on 2025-01-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ful", "0009_alter_employees_options_alter_warehouses_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobtitle",
            options={"verbose_name": "Должность", "verbose_name_plural": "Должности"},
        ),
    ]
