# Generated by Django 4.2.2 on 2025-01-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ful", "0010_alter_jobtitle_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="warehouses",
            old_name="slag",
            new_name="slug",
        ),
    ]
