# Generated by Django 4.2.2 on 2025-01-08 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование товара",
                        max_length=100,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True,
                        help_text="Введите артикул товара",
                        max_length=20,
                        null=True,
                        verbose_name="артикул",
                    ),
                ),
                (
                    "barcode",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Введите штрихкод товара",
                        null=True,
                        verbose_name="штрихкод",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="количество товара"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение продукта",
                        null=True,
                        upload_to="product/image",
                        verbose_name="Изображение(превью)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активный"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание продукта",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату создания",
                        null=True,
                        verbose_name="Дата создания(записи в БД)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату изменения",
                        null=True,
                        verbose_name="Дата последнего изменения(записи в БД)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца товара",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
