# Generated by Django 4.2.2 on 2025-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
    ]
