# Generated by Django 4.2.2 on 2025-01-12 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cabinet", "0003_alter_product_barcode_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца личного кабинета",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца личного кабинета",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cabinet.product",
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Владелец кабинета",
                "verbose_name_plural": "Владельцы кабинетов",
            },
        ),
    ]
