# Generated by Django 4.2.2 on 2025-01-12 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0005_alter_dashboard_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="продукты личного кабинета",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="cabinet.product",
                verbose_name="продукт",
            ),
        ),
    ]
