# Generated by Django 4.2.2 on 2025-01-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0006_alter_dashboard_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Введите наименование дашборда",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Наименование",
            ),
        ),
    ]
