# Generated by Django 4.2.2 on 2025-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0007_dashboard_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество товара"
            ),
        ),
    ]
