# Generated by Django 4.2.2 on 2025-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0008_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="количество товара"
            ),
        ),
    ]
