# Generated by Django 4.2.2 on 2025-01-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cabinet", "0010_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="товар личного кабинета",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="cabinet.product",
                verbose_name="товар",
            ),
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="Укажите дату, когда приедет товар",
                        verbose_name="Дата поступления товара",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Укажите количество товара, который приедет",
                        verbose_name="количество товара",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CD", "Создана"),
                            ("AE", "Приемка"),
                            ("FD", "Принята"),
                        ],
                        default="CD",
                        max_length=2,
                        verbose_name="Статус перевозки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца личного кабинета",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="товар личного кабинета",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_supply",
                        to="cabinet.product",
                        verbose_name="товар",
                    ),
                ),
            ],
        ),
    ]
