# Generated by Django 4.2.2 on 2025-01-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0011_alter_dashboard_product_supply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supply",
            options={"verbose_name": "Поставка", "verbose_name_plural": "Поставки"},
        ),
    ]
