# Generated by Django 4.2.2 on 2025-01-18 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cabinet", "0013_remove_supply_product_supply_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supply",
            name="product",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="quantity",
        ),
        migrations.AddField(
            model_name="supply",
            name="quantity_cargo",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество грузовых мест в поставке",
                verbose_name="количество грузовых мест",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца поставки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="status",
            field=models.CharField(
                choices=[
                    ("CD", "Создана"),
                    ("WY", "В пути"),
                    ("AE", "Приемка"),
                    ("FD", "Принята"),
                ],
                default="CD",
                max_length=2,
                verbose_name="Статус перевозки",
            ),
        ),
        migrations.CreateModel(
            name="ProductAccept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Укажите количество товара, который приедет",
                        verbose_name="количество товара",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца товара",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        help_text="Добавьте товар",
                        related_name="product_supply",
                        to="cabinet.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите в какой поставке приедет",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply",
                        to="cabinet.supply",
                        verbose_name="Поставка",
                    ),
                ),
            ],
        ),
    ]
