# Generated by Django 4.2.2 on 2025-01-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0014_remove_supply_product_remove_supply_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создана"),
                    ("WAY", "В пути"),
                    ("ACCEPTANCE", "Приемка"),
                    ("ACCEPTED", "Принята"),
                ],
                default="CREATED",
                max_length=10,
                verbose_name="Статус перевозки",
            ),
        ),
    ]
