# Generated by Django 4.2.2 on 2025-01-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0015_alter_supply_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="product",
        ),
    ]
