# Generated by Django 4.2.2 on 2025-01-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0016_remove_dashboard_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productaccept",
            options={
                "verbose_name": "Поступление товаров",
                "verbose_name_plural": "Поставления товаров",
            },
        ),
    ]
