# Generated by Django 4.2.2 on 2025-01-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0017_alter_productaccept_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productaccept",
            name="product",
        ),
        migrations.AddField(
            model_name="productaccept",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Добавьте товар",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_supply",
                to="cabinet.product",
                verbose_name="товар",
            ),
        ),
    ]
