# Generated by Django 4.2.2 on 2025-01-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0018_remove_productaccept_product_productaccept_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("В пути", "В пути"),
                    ("Приемка", "Приемка"),
                    ("Принята", "Принята"),
                ],
                default="Создана",
                max_length=10,
                verbose_name="Статус перевозки",
            ),
        ),
    ]
