# Generated by Django 4.2.2 on 2025-01-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cabinet", "0019_alter_supply_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название точки доставки",
                        max_length=100,
                        verbose_name="Название точки доставки",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Укажите город доставки",
                        max_length=30,
                        verbose_name="Город нахождения точки доставки",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Укажите адрес доставки",
                        max_length=100,
                        verbose_name="Адрес точки доставки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название макретплейса",
                        max_length=100,
                        verbose_name="Название маркетплейса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маркетплейс",
                "verbose_name_plural": "Маркетплейсы",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_date",
                    models.DateField(
                        help_text="Укажите дату отгрузки товар",
                        verbose_name="Дата отгрузки товара",
                    ),
                ),
                (
                    "quantity_cargo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество грузовых мест в поставке",
                        verbose_name="количество грузовых мест",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Отправлена", "Отправлена"),
                            ("Доставлена", "Доставлена"),
                        ],
                        default="Создана",
                        max_length=10,
                        verbose_name="Статус отгрузки",
                    ),
                ),
                (
                    "delivery_point",
                    models.ForeignKey(
                        help_text="Укажите куда доставить товар",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_point",
                        to="cabinet.deliverypoint",
                        verbose_name="Точка доставки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца поставки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отгрузка",
                "verbose_name_plural": "Отгрузки",
            },
        ),
        migrations.CreateModel(
            name="ProductShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Укажите количество товара, который приедет",
                        verbose_name="количество товара",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите владельца товара",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Добавьте товар",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_shipment",
                        to="cabinet.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите в какой отгрузке уедет",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment",
                        to="cabinet.shipment",
                        verbose_name="Отгрузка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отгрузка товара",
                "verbose_name_plural": "Отгрузки товаров",
            },
        ),
        migrations.AddField(
            model_name="deliverypoint",
            name="marketplace",
            field=models.ForeignKey(
                help_text="Укажите маркетплейс",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marketplace",
                to="cabinet.marketplace",
                verbose_name="Маркетплейс",
            ),
        ),
    ]
