# Generated by Django 4.2.2 on 2025-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0020_deliverypoint_marketplace_shipment_productshipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Укажите комментарий, либо адрес доставки, если нет в списке",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
    ]
