# Generated by Django 4.2.2 on 2025-01-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0021_shipment_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverypoint",
            options={
                "verbose_name": "Адрес доставки",
                "verbose_name_plural": "Адреса доставки",
            },
        ),
        migrations.AlterModelOptions(
            name="productaccept",
            options={
                "verbose_name": "Поступление товаров",
                "verbose_name_plural": "Поступления товаров",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания(записи в БД)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Введите наименование товара",
                max_length=100,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="количество товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now=True,
                help_text="Укажите дату изменения",
                null=True,
                verbose_name="Дата последнего изменения(записи в БД)",
            ),
        ),
    ]
