# Generated by Django 4.2.2 on 2025-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0022_alter_deliverypoint_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование компании",
                        max_length=100,
                        verbose_name="Наименование компании",
                    ),
                ),
                (
                    "inn",
                    models.IntegerField(
                        help_text="Укажите ИНН компании", verbose_name="ИНН компании"
                    ),
                ),
                (
                    "current_account",
                    models.IntegerField(
                        help_text="Укажите расчетный счет компании",
                        verbose_name="Расчетный счет компании",
                    ),
                ),
                (
                    "bic",
                    models.IntegerField(
                        help_text="Укажите БИК банка", verbose_name="БИК банка"
                    ),
                ),
                (
                    "legal_address",
                    models.TextField(
                        help_text="Введите юр. адрес", verbose_name="Юридическая адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
    ]
